# globals
BIN_DIR=bin

## fab-agon-emulator
EMULATOR=fab-agon-emulator
EMULATOR_DIR=$(EMULATOR)
EMULATOR_BIN=$(EMULATOR)
EMULATOR_BIN_SOURCE_PATH=$(EMULATOR_DIR)/$(EMULATOR_BIN)
EMULATOR_BIN_TARGET_PATH=$(BIN_DIR)/$(EMULATOR_BIN)

### fab-agon-emulator sdcard
SDCARD=sdcard
SDCARD_SOURCE_DIR=$(EMULATOR_DIR)/$(SDCARD)
SDCARD_TARGET_DIR=$(SDCARD)

### fab-agon-emulator firmware
FIRMWARE=firmware
FIRMWARE_SOURCE_DIR=$(EMULATOR_DIR)/$(FIRMWARE)
FIRMWARE_TARGET_DIR=$(FIRMWARE)

## sjasmplus
SJASM=sjasmplus
SJASM_DIR=$(SJASM)
SJASM_BIN=$(SJASM)
SJASM_BIN_SOURCE_PATH=$(SJASM_DIR)/$(SJASM_BIN)
SJASM_BIN_TARGET_PATH=$(BIN_DIR)/$(SJASM_BIN)

## agon-ez80asm
EZ80ASM=agon-ez80asm
EZ80ASM_DIR=$(EZ80ASM)
EZ80ASM_BIN=ez80asm
EZ80ASM_BIN_SOURCE_PATH=$(EZ80ASM_DIR)/bin/$(EZ80ASM_BIN)
EZ80ASM_BIN_TARGET_PATH=$(BIN_DIR)/$(EZ80ASM_BIN)

## Agon-CPM2.2
CPM=Agon-CPM2.2
CPM_DIR=$(CPM)
CPM_SYS=cpm.sys
CPM_BIN=cpm.bin
CPM_MAIN_ASM=main.asm
CPM_BOOTSTRAP_ASM=cpm.asm
#
CPM_SRC_DIR=$(CPM_DIR)/sources
CPM_BOOTSTRAP_DIR=$(CPM_DIR)/bootstrap
CPM_DISKS_DIR=$(CPM_DIR)/disks
#
CPM_MAIN_ASM_PATH=$(CPM_SRC_DIR)/$(CPM_MAIN_ASM)
CPM_SYS_SOURCE_PATH=$(CPM_SYS)
CPM_SYS_INTERMEDIATE_PATH=$(CPM_BOOTSTRAP_DIR)/$(CPM_SYS)
#
CPM_TARGET_DIR=$(SDCARD_TARGET_DIR)/$(CPM)
CPM_BIN_SOURCE_PATH=$(CPM_BOOTSTRAP_DIR)/$(CPM_BIN)
CPM_BIN_TARGET_PATH=$(CPM_TARGET_DIR)/$(CPM_BIN)
#
CPM_DISKS_SOURCE_DIR=$(CPM_DISKS_DIR)
CPM_DISKS_SOURCE_PATH=$(CPM_DISKS_SOURCE_DIR)/*.dsk
CPM_DISKS_TARGET_DIR=$(CPM_TARGET_DIR)
CPM_DISKP_SOURCE_PATH=$(CPM_DISKS_SOURCE_DIR)/cpmp.dsk
CPM_DISKP_TARGET_PATH=$(CPM_DISKS_TARGET_DIR)/cpmp.dsk
#
OVERRIDES_DIR=scripts
AUTOEXEC_BASIC_SOURCE_PATH=$(OVERRIDES_DIR)/autoexec.basic.txt
AUTOEXEC_BASIC24_SOURCE_PATH=$(OVERRIDES_DIR)/autoexec.basic24.txt
AUTOEXEC_CPM_SOURCE_PATH=$(OVERRIDES_DIR)/autoexec.cpm.txt
AUTOEXEC_TARGET_PATH=$(SDCARD_TARGET_DIR)/autoexec.txt

# Rules
all: emulator cpm

# .PHONY: autoexec-basic autoexec-basic24 autoexec-cpm

emulator: $(EMULATOR_BIN_TARGET_PATH) $(SDCARD_TARGET_DIR) $(FIRMWARE_TARGET_DIR)
cpm: sjasm ez80asm cpmbuild
sjasm: $(SJASM_BIN_TARGET_PATH)
ez80asm: $(EZ80ASM_BIN_TARGET_PATH)
cpmbuild: emulator $(CPM_BIN_TARGET_PATH) $(CPM_DISKP_TARGET_PATH)

autoexec-clean:
	rm -f $(AUTOEXEC_TARGET_PATH)

autoexec-basic:
	cp -f $(AUTOEXEC_BASIC_SOURCE_PATH) $(AUTOEXEC_TARGET_PATH)

autoexec-basic24:
	cp -f $(AUTOEXEC_BASIC24_SOURCE_PATH) $(AUTOEXEC_TARGET_PATH)

autoexec-cpm:
	cp -f $(AUTOEXEC_CPM_SOURCE_PATH) $(AUTOEXEC_TARGET_PATH)

autoexec-electron:
	cp -f $(AUTOEXEC_ELECTRON_SOURCE_PATH) $(AUTOEXEC_TARGET_PATH)

$(EMULATOR_BIN_TARGET_PATH):
	@echo === Building $(EMULATOR)
	$(MAKE) -C $(EMULATOR_DIR) all
	cp $(EMULATOR_BIN_SOURCE_PATH) $(EMULATOR_BIN_TARGET_PATH)

$(SDCARD_TARGET_DIR):
	@echo === Preparing $(SDCARD_TARGET_DIR)
	cp -r $(SDCARD_SOURCE_DIR) $(SDCARD_TARGET_DIR)

$(FIRMWARE_TARGET_DIR):
	@echo === Preparing $(FIRMWARE_TARGET_DIR):
	cp -r $(FIRMWARE_SOURCE_DIR) $(FIRMWARE_TARGET_DIR)

$(SJASM_BIN_TARGET_PATH):
	@echo === Building $(SJASM)
	$(MAKE) -C $(SJASM_DIR) all
	cp $(SJASM_BIN_SOURCE_PATH) $(SJASM_BIN_TARGET_PATH)

$(EZ80ASM_BIN_TARGET_PATH):
	@echo === Building $(EZ80ASM)
	-$(MAKE) -C $(EZ80ASM_DIR) all
	cp $(EZ80ASM_BIN_SOURCE_PATH) $(EZ80ASM_BIN_TARGET_PATH)

$(CPM_BIN_TARGET_PATH):
	@echo === Building $(CPM)
	mkdir -p $(CPM_TARGET_DIR)
	$(SJASM_BIN_TARGET_PATH) $(CPM_MAIN_ASM_PATH)
	mv $(CPM_SYS_SOURCE_PATH) $(CPM_SYS_INTERMEDIATE_PATH)
	@cd $(CPM_BOOTSTRAP_DIR) && \
		../../$(EZ80ASM_BIN_TARGET_PATH) $(CPM_BOOTSTRAP_ASM)
	mv $(CPM_BIN_SOURCE_PATH) $(CPM_BIN_TARGET_PATH)

$(CPM_DISKP_SOURCE_PATH):
	@echo === Building $(CPM_DISKP_SOURCE_PATH):
	cd $(CPM_DISKS_DIR) && \
		./build.sh

$(CPM_DISKP_TARGET_PATH): $(CPM_DISKP_SOURCE_PATH)
	@echo === Copying disks to $(CPM_DISKS_TARGET_DIR)
	cp $(CPM_DISKS_SOURCE_PATH) $(CPM_DISKS_TARGET_DIR)

